# Generated by Django 4.1.1 on 2022-09-25 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarquest_app', '0002_remove_user_displayname_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='has_FinalExam',
            field=models.BooleanField(default=False),
        ),
    ]
