# Generated by Django 4.1.1 on 2022-09-26 00:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarquest_app', '0003_alter_course_has_finalexam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='totalMidTerms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='gradeWeight',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
