# Generated by Django 4.1.1 on 2022-11-02 01:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarquest_app', '0006_rename_grade_course_finalgrade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='currentGrade',
            field=models.IntegerField(default=-1, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='finalGrade',
            field=models.IntegerField(blank=True, default=-1, null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
