# Generated by Django 4.1.1 on 2022-11-05 02:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarquest_app', '0007_alter_course_currentgrade_alter_course_finalgrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='currentGrade',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=4, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='finalGrade',
            field=models.DecimalField(blank=True, decimal_places=1, default=-1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
