# Generated by Django 4.1.1 on 2022-11-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarquest_app', '0009_usertracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagereport',
            name='graphImage',
            field=models.BinaryField(blank=True),
        ),
        migrations.AddField(
            model_name='usagereport',
            name='status',
            field=models.CharField(choices=[('deleted', 'Deleted'), ('viewable', 'viewable')], default='viewable', max_length=50),
        ),
    ]
